name: First_Workflow

on:
  push:
    # Trigger on push to any branch
  pull_request:
    # Trigger on pull requests to any branch
  # Allow manual trigger
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run first job tasks
        run: |
          echo "Running first job tasks"
          echo "First workflow completed successfully"
          
      - name: Report status
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.sha;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'success',
              context: 'First Workflow Status',
              description: 'First workflow completed successfully'
            });