name: Second_Workflow

on:
  workflow_run:
    workflows: [First_Workflow]
    types:
      - completed
    branches:
      - '**'  # Run on all branches

jobs:
  second-job:
    runs-on: ubuntu-latest
    # Only run if the first workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run second job tasks
        run: |
          echo "Running second job tasks"
          echo "Second workflow completed successfully"