name: Second_Workflow

on:
  workflow_run:
    workflows: [First_Workflow]
    types:
      - completed
    branches:
      - '**'  # Run on all branches

jobs:
  second-job:
    runs-on: ubuntu-latest
    # Only run if the first workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run second job tasks
        run: |
          echo "Running second job tasks"
          echo "Second workflow completed successfully"
          
      - name: Report status
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.payload.workflow_run.head_sha;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'success',
              context: 'Second Workflow Status',
              description: 'Second workflow completed successfully'
            });