name: Final_Workflow

on:
  workflow_run:
    workflows: [Second_Workflow]
    types:
      - completed
    branches:
      - '**'  # Run on all branches

jobs:
  third-job:
    runs-on: ubuntu-latest
    # Only run if the second workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run third job tasks
        run: |
          echo "Running third job tasks"
          echo "Third part completed successfully"
  
  fourth-job:
    needs: third-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run fourth job tasks
        run: |
          echo "Running fourth job tasks"
          echo "Fourth part completed successfully"
          
      - name: Final success message
        run: echo "All workflows have completed successfully!"