name: Third Workflow

on:
  workflow_run:
    workflows: [Second Workflow]
    types:
      - completed

jobs:
  third-job:
    runs-on: ubuntu-latest
    # Only run if the second workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run third job tasks
        run: |
          echo "Running third job tasks"
          echo "Third workflow completed successfully"