name: Fourth Workflow

on:
  workflow_run:
    workflows: [Third Workflow]
    types:
      - completed

jobs:
  fourth-job:
    runs-on: ubuntu-latest
    # Only run if the third workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run fourth job tasks
        run: |
          echo "Running fourth job tasks"
          echo "Fourth workflow completed successfully"
          
      - name: Final success message
        run: echo "All workflows have completed successfully!"