# .github/workflows/test.yml
name: Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  run-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests"
      - run: exit 1
